Fix Elixir 1.20.0-rc.0 warnings
Mainly this involves using the pin operator (`^`) in binary pattern
matches where the size is matched out of a binary.
`Mint.WebSocket.Frame.decode_opcode/1` is also refactored to pattern
match the map directly, resolving this warning:

     warning: incompatible types given to Map.fetch/2:

         Map.fetch(
           %{
             <<0::integer-size(4), ""::binary>> => :continuation,
             <<1::integer-size(4), ""::binary>> => :text,
             <<2::integer-size(4), ""::binary>> => :binary,
             <<8::integer-size(4), ""::binary>> => :close,
             <<9::integer-size(4), ""::binary>> => :ping,
             <<10::integer-size(4), ""::binary>> => :pong
           },
           opcode
         )

     the map:

         dynamic(%{bitstring() => :binary or :close or :continuation or :ping or :pong or :text})

     does not have all required keys:

         dynamic()

     therefore this function will always return :error

     where "opcode" was given the type:

         # type: dynamic()
         # from: lib/mint/web_socket/frame.ex:289:22
         opcode

     typing violation found at:
     │
 290 │     with :error <- Map.fetch(@reverse_opcodes, opcode) do
     │                        ~
     │
     └─ lib/mint/web_socket/frame.ex:290:24: Mint.WebSocket.Frame.decode_opcode/1